server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}

spring:
  application:
    name: product-service